hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ../board/gcc_flash.ld
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_DEBUG_MODE: 1
  CONFIG_KERNEL_NONE: 1
  CONFIG_SUPPORT_TSPEND: 1
  CONFIG_XIP: 1
name: demo
version: v0.0.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - A3F011_CPU0_demo: v0.0.0
  - sdk_011_CPU0: v0.0.0
build_config:
  include:
    - include
    - ./
  internal_include: 
  cflag: -O0   -Wall  -ffunction-sections  -fdata-sections
  cxxflag: -O0   -Wall  -ffunction-sections  -fdata-sections
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/main.c
  - src/user_demo.c
depends_forward:
  - A3F011_CPU0_demo: v0.0.0
  - sdk_011_CPU0: v0.0.0
install: 
homepage: 